# Generated by Django 4.1.5 on 2023-01-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_alter_song_playlists'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='followed_artists',
            field=models.ManyToManyField(blank=True, related_name='followers', to='user.artist'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='liked_playlists',
            field=models.ManyToManyField(blank=True, related_name='liked_customers', to='song.playlist'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='liked_customers', to='song.song'),
        ),
    ]
