# Generated by Django 4.1.5 on 2023-03-31 17:40

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customer_gender'),
        ('song', '0004_playlist_hide_alter_song_artists_alter_song_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='user.customer'),
        ),
    ]
